import { ICoupon } from "@src/interfaces/coupon.interface";
import { COUPON_TYPE } from "./enum/coupon.enum";

export const coupons: ICoupon[] = [
  // Discount Coupons
  {
    id: 1,
    name: "รับส่วนลด 10 % สูงสุด 100 ฿",
    description: "สามารถใช้งานได้ถึง 12 Dec 2025",
    tag: "พิเศษเฉพาะคุณ",
    recommend: true,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 2,
    name: "ลดทันที 200 ฿ เมื่อซื้อครับ 2,000 ฿",
    description: "สามารถใช้งานได้ถึง 15 Jan 2026",
    tag: "Hot Deal",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 3,
    name: "ส่วนลด 15% สูงสุด 500 ฿",
    description: "สามารถใช้งานได้ถึง 31 Mar 2026",
    tag: "ลูกค้าใหม่",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 4,
    name: "ลด 50 ฿ ไม่มีขั้นต่ำ",
    description: "สามารถใช้งานได้ถึง 28 Feb 2026",
    tag: "ทุกคน",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 5,
    name: "ลดทันที 1,000 ฿ เมื่อซื้อครบ 10,000 ฿",
    description: "สามารถใช้งานได้ถึง 30 Jun 2026",
    tag: "Big Sale",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 6,
    name: "ส่วนลด 20% สูงสุด 300 ฿",
    description: "สามารถใช้งานได้ถึง 15 Apr 2026",
    tag: "สมาชิกVIP",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 7,
    name: "ลดทันที 150 ฿ เมื่อซื้อครบ 1,500 ฿",
    description: "สามารถใช้งานได้ถึง 20 May 2026",
    tag: "Flash Sale",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  {
    id: 8,
    name: "ส่วนลด 25% สูงสุด 800 ฿",
    description: "สามารถใช้งานได้ถึง 31 Dec 2025",
    tag: "Year End",
    recommend: false,
    type: COUPON_TYPE.DISCOUNT,
  },
  // Freebie Coupons
  {
    id: 9,
    name: "แผ่นรองเมาส์เกมมิ่ง ฟรี",
    description: "รับแผ่นรองเมาส์เกมมิ่งฟรี เมื่อซื้อเมาส์ครบ 1,500 ฿",
    tag: "ของแถม",
    recommend: true,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 10,
    name: "สายชาร์จ USB-C ฟรี",
    description: "รับสายชาร์จ USB-C ฟรี เมื่อซื้อสินค้าครบ 3,000 ฿",
    tag: "ของแถม",
    recommend: false,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 11,
    name: "คีย์แคป Custom ฟรี",
    description: "รับคีย์แคปสีพิเศษฟรี เมื่อซื้อคีย์บอร์ดครบ 2,500 ฿",
    tag: "Limited",
    recommend: true,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 12,
    name: "ถุงผ้าแบรนด์ ฟรี",
    description: "รับถุงผ้าแคนวาสฟรี เมื่อซื้อสินค้าครบ 1,000 ฿",
    tag: "ของแถม",
    recommend: false,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 13,
    name: "พัดลมเคส RGB ฟรี",
    description: "รับพัดลมเคส RGB ฟรี เมื่อซื้อเคสครบ 5,000 ฿",
    tag: "Premium",
    recommend: true,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 14,
    name: "สติ๊กเกอร์แพค ฟรี",
    description: "รับสติ๊กเกอร์แบรนด์ฟรี เมื่อซื้อสินค้าครบ 500 ฿",
    tag: "ของแถม",
    recommend: false,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 15,
    name: "ขาตั้งหูฟัง ฟรี",
    description: "รับขาตั้งหูฟังฟรี เมื่อซื้อหูฟังครบ 2,000 ฿",
    tag: "ของแถม",
    recommend: true,
    type: COUPON_TYPE.FREEBIE,
  },
  {
    id: 16,
    name: "แผ่นรองแก้ว ฟรี",
    description: "รับแผ่นรองแก้วฟรี เมื่อซื้อสินค้าครบ 800 ฿",
    tag: "ของแถม",
    recommend: false,
    type: COUPON_TYPE.FREEBIE,
  },
  // Brand Coupons
  {
    id: 17,
    name: "ASUS ส่วนลดพิเศษ 15%",
    description: "ส่วนลดพิเศษสำหรับสินค้า ASUS ทุกชิ้น สูงสุด 2,000 ฿",
    tag: "แบรนด์ดัง",
    recommend: true,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 18,
    name: "MSI Gaming Sale 20%",
    description: "ส่วนลดสินค้า MSI Gaming ทุกชิ้น สูงสุด 3,000 ฿",
    tag: "Gaming",
    recommend: true,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 19,
    name: "Corsair Memory Deal",
    description: "ลดทันที 500 ฿ เมื่อซื้อหน่วยความจำ Corsair",
    tag: "Memory",
    recommend: false,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 20,
    name: "Intel Processor Special",
    description: "ส่วนลด 10% สำหรับโปรเซสเซอร์ Intel ทุกรุ่น",
    tag: "CPU",
    recommend: true,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 21,
    name: "AMD Ryzen Promotion",
    description: "ส่วนลด 12% สำหรับโปรเซสเซอร์ AMD Ryzen ทุกรุ่น",
    tag: "CPU",
    recommend: false,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 22,
    name: "Samsung SSD Flash Sale",
    description: "ส่วนลด 25% สำหรับ SSD Samsung ทุกรุ่น สูงสุด 1,500 ฿",
    tag: "Storage",
    recommend: true,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 23,
    name: "Gigabyte Motherboard Deal",
    description: "ลดทันที 800 ฿ เมื่อซื้อเมนบอร์ด Gigabyte",
    tag: "Motherboard",
    recommend: false,
    type: COUPON_TYPE.BRAND,
  },
  {
    id: 24,
    name: "Logitech Peripheral Sale",
    description: "ส่วนลด 30% สำหรับเมาส์และคีย์บอร์ด Logitech",
    tag: "Peripheral",
    recommend: true,
    type: COUPON_TYPE.BRAND,
  },
];
