import { IProduct } from "@src/interfaces/product.interface";

import product from "../../public/assets/svgs/product/product.svg";
import productHead1 from "../../public/assets/svgs/product/product-head1.svg";
import productHead2 from "../../public/assets/svgs/product/product-head2.svg";
import productHead3 from "../../public/assets/svgs/product/product-head3.svg";
import headIcon1 from "../../public/assets/svgs/product/head-icon1.svg";
import headIcon2 from "../../public/assets/svgs/product/head-icon2.svg";
import headIcon3 from "../../public/assets/svgs/product/head-icon3.svg";

import { PRODUCT_CATEGORY, PRODUCT_TYPE } from "./enum/product.enum";

export const products: IProduct[] = [
  // KEYBOARD Products - GAMING (5 ชิ้น)
  {
    id: 1,
    name: "Corsair K95 RGB Platinum XT Gaming Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GAMING,
    price: 18990,
    realPrice: 21990,
    discount: 14,
    image: product,
    sold: 45,
    stock: 50,
    soldCountPercentage: 90,
    viewCount: 1250,
  },
  {
    id: 2,
    name: "Razer Huntsman V3 Pro TKL Gaming Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GAMING,
    price: 16990,
    realPrice: 19990,
    discount: 15,
    image: product,
    sold: 32,
    stock: 40,
    soldCountPercentage: 80,
    viewCount: 980,
  },
  {
    id: 3,
    name: "Logitech G Pro X TKL Gaming Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GAMING,
    price: 14990,
    realPrice: 17990,
    discount: 17,
    image: product,
    sold: 68,
    stock: 75,
    soldCountPercentage: 91,
    viewCount: 1580,
  },
  {
    id: 4,
    name: "SteelSeries Apex Pro TKL Gaming Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GAMING,
    price: 12990,
    realPrice: 14990,
    discount: 13,
    image: product,
    sold: 89,
    stock: 100,
    soldCountPercentage: 89,
    viewCount: 2100,
  },
  {
    id: 5,
    name: "HyperX Alloy Origins 65 Gaming Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GAMING,
    price: 9990,
    realPrice: 11990,
    discount: 17,
    image: product,
    sold: 156,
    stock: 200,
    soldCountPercentage: 78,
    viewCount: 3250,
  },

  // KEYBOARD Products - GRAPHIC (5 ชิ้น)
  {
    id: 6,
    name: "Keychron Q1 Pro QMK Wireless Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 8990,
    realPrice: 10990,
    discount: 18,
    image: product,
    sold: 234,
    stock: 300,
    soldCountPercentage: 78,
    viewCount: 4100,
  },
  {
    id: 7,
    name: "Apple Magic Keyboard Pro",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 17990,
    realPrice: 20990,
    discount: 14,
    image: product,
    sold: 56,
    stock: 80,
    soldCountPercentage: 70,
    viewCount: 1890,
  },
  {
    id: 8,
    name: "Logitech MX Keys Advanced Wireless Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 15990,
    realPrice: 18990,
    discount: 16,
    image: product,
    sold: 78,
    stock: 120,
    soldCountPercentage: 65,
    viewCount: 2300,
  },
  {
    id: 9,
    name: "Dell Alienware AW510K Gaming Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 13990,
    realPrice: 16490,
    discount: 15,
    image: product,
    sold: 145,
    stock: 180,
    soldCountPercentage: 81,
    viewCount: 2890,
  },
  {
    id: 10,
    name: "ASUS ROG Strix Scope II 96 Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 11990,
    realPrice: 13990,
    discount: 14,
    image: product,
    sold: 198,
    stock: 250,
    soldCountPercentage: 79,
    viewCount: 3450,
  },

  // KEYBOARD Products - ANIMATION (5 ชิ้น)
  {
    id: 11,
    name: "Leopold FC750R PD Mechanical Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.ANIMATION,
    price: 8990,
    realPrice: 10590,
    discount: 15,
    image: product,
    sold: 267,
    stock: 320,
    soldCountPercentage: 83,
    viewCount: 4200,
  },
  {
    id: 12,
    name: "Varmilo MA87M Moonlight Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.ANIMATION,
    price: 7990,
    realPrice: 9390,
    discount: 15,
    image: product,
    sold: 345,
    stock: 400,
    soldCountPercentage: 86,
    viewCount: 5100,
  },
  {
    id: 13,
    name: "Ducky One 3 Mini Pure White 60% Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.ANIMATION,
    price: 4990,
    realPrice: 5890,
    discount: 15,
    image: product,
    sold: 189,
    stock: 250,
    soldCountPercentage: 76,
    viewCount: 3800,
  },
  {
    id: 14,
    name: "Akko 3084B Plus Wireless Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.ANIMATION,
    price: 3990,
    realPrice: 4690,
    discount: 15,
    image: product,
    sold: 278,
    stock: 350,
    soldCountPercentage: 79,
    viewCount: 4500,
  },
  {
    id: 15,
    name: "Royal Kludge RK61 Wireless Keyboard",
    category: PRODUCT_CATEGORY.KEYBOARD,
    type: PRODUCT_TYPE.ANIMATION,
    price: 2990,
    realPrice: 3490,
    discount: 14,
    image: product,
    sold: 234,
    stock: 300,
    soldCountPercentage: 78,
    viewCount: 3200,
  },

  // MOUSE Products - GAMING (5 ชิ้น)
  {
    id: 16,
    name: "Logitech G Pro X Superlight 2 Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GAMING,
    price: 65990,
    realPrice: 75990,
    discount: 13,
    image: product,
    sold: 12,
    stock: 15,
    soldCountPercentage: 80,
    viewCount: 850,
  },
  {
    id: 17,
    name: "Razer DeathAdder V3 Pro Wireless Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GAMING,
    price: 45990,
    realPrice: 52990,
    discount: 13,
    image: product,
    sold: 28,
    stock: 35,
    soldCountPercentage: 80,
    viewCount: 1200,
  },
  {
    id: 18,
    name: "SteelSeries Rival 650 Wireless Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GAMING,
    price: 35990,
    realPrice: 41990,
    discount: 14,
    image: product,
    sold: 45,
    stock: 50,
    soldCountPercentage: 90,
    viewCount: 1650,
  },
  {
    id: 19,
    name: "Corsair Dark Core RGB Pro SE Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GAMING,
    price: 28990,
    realPrice: 33990,
    discount: 15,
    image: product,
    sold: 67,
    stock: 80,
    soldCountPercentage: 84,
    viewCount: 2100,
  },
  {
    id: 20,
    name: "HyperX Pulsefire Haste 2 Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GAMING,
    price: 22990,
    realPrice: 26990,
    discount: 15,
    image: product,
    sold: 89,
    stock: 100,
    soldCountPercentage: 89,
    viewCount: 2850,
  },

  // MOUSE Products - GRAPHIC (5 ชิ้น)
  {
    id: 21,
    name: "Logitech MX Master 3S Wireless Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 16990,
    realPrice: 19990,
    discount: 15,
    image: product,
    sold: 178,
    stock: 200,
    soldCountPercentage: 89,
    viewCount: 3900,
  },
  {
    id: 22,
    name: "Apple Magic Mouse 2 Space Gray",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 18990,
    realPrice: 22490,
    discount: 16,
    image: product,
    sold: 156,
    stock: 180,
    soldCountPercentage: 87,
    viewCount: 3200,
  },
  {
    id: 23,
    name: "Microsoft Surface Precision Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 13990,
    realPrice: 16490,
    discount: 15,
    image: product,
    sold: 234,
    stock: 280,
    soldCountPercentage: 84,
    viewCount: 4100,
  },
  {
    id: 24,
    name: "Razer Pro Click Mini Wireless Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 11990,
    realPrice: 13990,
    discount: 14,
    image: product,
    sold: 298,
    stock: 350,
    soldCountPercentage: 85,
    viewCount: 4800,
  },
  {
    id: 25,
    name: "Logitech MX Anywhere 3 Wireless Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 15990,
    realPrice: 18990,
    discount: 16,
    image: product,
    sold: 167,
    stock: 200,
    soldCountPercentage: 84,
    viewCount: 3600,
  },

  // MOUSE Products - ANIMATION (5 ชิ้น)
  {
    id: 26,
    name: "Wacom Intuos Pro Creative Pen Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 14990,
    realPrice: 17590,
    discount: 15,
    image: product,
    sold: 198,
    stock: 250,
    soldCountPercentage: 79,
    viewCount: 3800,
  },
  {
    id: 27,
    name: "Logitech G203 LIGHTSYNC Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 12990,
    realPrice: 15290,
    discount: 15,
    image: product,
    sold: 267,
    stock: 320,
    soldCountPercentage: 83,
    viewCount: 4200,
  },
  {
    id: 28,
    name: "Razer Basilisk V3 X HyperSpeed Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 10990,
    realPrice: 12890,
    discount: 15,
    image: product,
    sold: 345,
    stock: 400,
    soldCountPercentage: 86,
    viewCount: 5100,
  },
  {
    id: 29,
    name: "SteelSeries Sensei Ten Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 8990,
    realPrice: 10590,
    discount: 15,
    image: product,
    sold: 289,
    stock: 350,
    soldCountPercentage: 83,
    viewCount: 4500,
  },
  {
    id: 30,
    name: "Corsair M65 RGB Elite Gaming Mouse",
    category: PRODUCT_CATEGORY.MOUSE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 6990,
    realPrice: 8190,
    discount: 15,
    image: product,
    sold: 234,
    stock: 300,
    soldCountPercentage: 78,
    viewCount: 3900,
  },

  // MONITOR Products - GAMING (5 ชิ้น)
  {
    id: 31,
    name: 'ASUS ROG Swift PG32UQX 32" 4K HDR Gaming Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GAMING,
    price: 4990,
    realPrice: 5990,
    discount: 17,
    image: product,
    sold: 145,
    stock: 150,
    soldCountPercentage: 97,
    viewCount: 2800,
  },
  {
    id: 32,
    name: 'Alienware AW3423DW 34" OLED Gaming Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GAMING,
    price: 5490,
    realPrice: 6490,
    discount: 15,
    image: product,
    sold: 98,
    stock: 120,
    soldCountPercentage: 82,
    viewCount: 2200,
  },
  {
    id: 33,
    name: 'Samsung Odyssey G9 49" Gaming Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GAMING,
    price: 2290,
    realPrice: 2690,
    discount: 15,
    image: product,
    sold: 267,
    stock: 300,
    soldCountPercentage: 89,
    viewCount: 4500,
  },
  {
    id: 34,
    name: 'LG UltraGear 27GP950-B 27" 4K Gaming Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GAMING,
    price: 8990,
    realPrice: 10990,
    discount: 18,
    image: product,
    sold: 56,
    stock: 80,
    soldCountPercentage: 70,
    viewCount: 1800,
  },
  {
    id: 35,
    name: 'Acer Predator X27 27" 4K G-Sync Gaming Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GAMING,
    price: 7990,
    realPrice: 9490,
    discount: 16,
    image: product,
    sold: 89,
    stock: 100,
    soldCountPercentage: 89,
    viewCount: 2400,
  },

  // MONITOR Products - GRAPHIC (5 ชิ้น)
  {
    id: 36,
    name: 'Apple Studio Display 27" 5K Retina Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 3490,
    realPrice: 3990,
    discount: 13,
    image: product,
    sold: 198,
    stock: 250,
    soldCountPercentage: 79,
    viewCount: 3200,
  },
  {
    id: 37,
    name: 'Dell UltraSharp U2723QE 27" 4K Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 2990,
    realPrice: 3490,
    discount: 14,
    image: product,
    sold: 234,
    stock: 280,
    soldCountPercentage: 84,
    viewCount: 3600,
  },
  {
    id: 38,
    name: 'ASUS ProArt PA278QV 27" Professional Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 2790,
    realPrice: 3290,
    discount: 15,
    image: product,
    sold: 289,
    stock: 350,
    soldCountPercentage: 83,
    viewCount: 4100,
  },
  {
    id: 39,
    name: 'LG UltraFine 4K 24" Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 1490,
    realPrice: 1790,
    discount: 17,
    image: product,
    sold: 345,
    stock: 400,
    soldCountPercentage: 86,
    viewCount: 4800,
  },
  {
    id: 40,
    name: 'BenQ SW321C 32" 4K Photo Editing Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 3790,
    realPrice: 4490,
    discount: 16,
    image: product,
    sold: 167,
    stock: 200,
    soldCountPercentage: 84,
    viewCount: 3200,
  },

  // MONITOR Products - ANIMATION (5 ชิ้น)
  {
    id: 41,
    name: 'Wacom Cintiq 22 22" Creative Pen Display',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.ANIMATION,
    price: 3990,
    realPrice: 4690,
    discount: 15,
    image: product,
    sold: 198,
    stock: 250,
    soldCountPercentage: 79,
    viewCount: 3400,
  },
  {
    id: 42,
    name: "Huion Kamvas 24 2.5K Pen Display",
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.ANIMATION,
    price: 5990,
    realPrice: 6990,
    discount: 14,
    image: product,
    sold: 134,
    stock: 180,
    soldCountPercentage: 74,
    viewCount: 2800,
  },
  {
    id: 43,
    name: "XP-Pen Artist 15.6 Pro Drawing Tablet Monitor",
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.ANIMATION,
    price: 1290,
    realPrice: 1490,
    discount: 13,
    image: product,
    sold: 267,
    stock: 320,
    soldCountPercentage: 83,
    viewCount: 4200,
  },
  {
    id: 44,
    name: 'Gaomon PD1561 15.6" Drawing Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.ANIMATION,
    price: 1190,
    realPrice: 1390,
    discount: 14,
    image: product,
    sold: 345,
    stock: 400,
    soldCountPercentage: 86,
    viewCount: 4600,
  },
  {
    id: 45,
    name: 'UGEE U1200 12" Graphics Drawing Monitor',
    category: PRODUCT_CATEGORY.MONITOR,
    type: PRODUCT_TYPE.ANIMATION,
    price: 990,
    realPrice: 1190,
    discount: 17,
    image: product,
    sold: 289,
    stock: 350,
    soldCountPercentage: 83,
    viewCount: 4000,
  },

  // SMARTPHONE Products - GAMING (5 ชิ้น)
  {
    id: 46,
    name: "iPhone 15 Pro Max 1TB Gaming Edition",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GAMING,
    price: 6990,
    realPrice: 7990,
    discount: 13,
    image: product,
    sold: 78,
    stock: 100,
    soldCountPercentage: 78,
    viewCount: 2100,
  },
  {
    id: 47,
    name: "Samsung Galaxy S24 Ultra 512GB Gaming",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GAMING,
    price: 3990,
    realPrice: 4690,
    discount: 15,
    image: product,
    sold: 134,
    stock: 150,
    soldCountPercentage: 89,
    viewCount: 2800,
  },
  {
    id: 48,
    name: "ASUS ROG Phone 8 Pro 256GB Gaming",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GAMING,
    price: 7490,
    realPrice: 8990,
    discount: 17,
    image: product,
    sold: 67,
    stock: 80,
    soldCountPercentage: 84,
    viewCount: 1900,
  },
  {
    id: 49,
    name: "Xiaomi Black Shark 5 Pro 256GB Gaming",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GAMING,
    price: 1990,
    realPrice: 2390,
    discount: 17,
    image: product,
    sold: 345,
    stock: 400,
    soldCountPercentage: 86,
    viewCount: 5200,
  },
  {
    id: 50,
    name: "Red Magic 9 Pro 128GB Gaming Phone",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GAMING,
    price: 1490,
    realPrice: 1790,
    discount: 17,
    image: product,
    sold: 289,
    stock: 350,
    soldCountPercentage: 83,
    viewCount: 4100,
  },

  // SMARTPHONE Products - GRAPHIC (5 ชิ้น)
  {
    id: 51,
    name: "iPhone 15 Pro 1TB for Photography",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 9990,
    realPrice: 11990,
    discount: 17,
    image: product,
    sold: 34,
    stock: 50,
    soldCountPercentage: 68,
    viewCount: 1200,
  },
  {
    id: 52,
    name: "Samsung Galaxy S24 Ultra 1TB Camera Pro",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 3490,
    realPrice: 4190,
    discount: 17,
    image: product,
    sold: 198,
    stock: 250,
    soldCountPercentage: 79,
    viewCount: 3200,
  },
  {
    id: 53,
    name: "Xiaomi 14 Ultra 512GB Photography",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 1790,
    realPrice: 2090,
    discount: 14,
    image: product,
    sold: 234,
    stock: 280,
    soldCountPercentage: 84,
    viewCount: 3600,
  },
  {
    id: 54,
    name: "Google Pixel 8 Pro 512GB Camera",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 5990,
    realPrice: 7190,
    discount: 17,
    image: product,
    sold: 89,
    stock: 120,
    soldCountPercentage: 74,
    viewCount: 2400,
  },
  {
    id: 55,
    name: "Oppo Find X7 Ultra 256GB Photography",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.GRAPHIC,
    price: 2990,
    realPrice: 3490,
    discount: 14,
    image: product,
    sold: 156,
    stock: 180,
    soldCountPercentage: 87,
    viewCount: 2800,
  },

  // SMARTPHONE Products - ANIMATION (5 ชิ้น)
  {
    id: 56,
    name: 'iPad Pro 12.9" 1TB for Animation',
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 2490,
    realPrice: 2890,
    discount: 14,
    image: product,
    sold: 267,
    stock: 320,
    soldCountPercentage: 83,
    viewCount: 3800,
  },
  {
    id: 57,
    name: "Samsung Galaxy Tab S9 Ultra 512GB",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 4990,
    realPrice: 5890,
    discount: 15,
    image: product,
    sold: 145,
    stock: 200,
    soldCountPercentage: 73,
    viewCount: 2600,
  },
  {
    id: 58,
    name: "OnePlus 12 Pro 256GB Creative",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 2990,
    realPrice: 3490,
    discount: 14,
    image: product,
    sold: 234,
    stock: 280,
    soldCountPercentage: 84,
    viewCount: 3400,
  },
  {
    id: 59,
    name: "Huawei Mate 60 Pro 256GB Creative",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 1290,
    realPrice: 1490,
    discount: 13,
    image: product,
    sold: 345,
    stock: 400,
    soldCountPercentage: 86,
    viewCount: 4200,
  },
  {
    id: 60,
    name: "Vivo X100 Pro 128GB Creative Phone",
    category: PRODUCT_CATEGORY.SMARTPHONE,
    type: PRODUCT_TYPE.ANIMATION,
    price: 990,
    realPrice: 1190,
    discount: 17,
    image: product,
    sold: 289,
    stock: 350,
    soldCountPercentage: 83,
    viewCount: 3800,
  },
];

export const productCategories = [
  {
    id: 1,
    label1: "นี่แหละ",
    label2: "สัมผัสที่ตามหา",
    icon: headIcon1,
    bgImage: productHead1,
    category: PRODUCT_CATEGORY.KEYBOARD,
  },
  {
    id: 2,
    label1: "ช็อตไหน",
    label2: "ยังไงก็ไม่พลาด",
    icon: headIcon2,
    bgImage: productHead2,
    category: PRODUCT_CATEGORY.MOUSE,
  },
  {
    id: 3,
    label1: "ภาพสวย",
    label2: "คมชัดทุกพิกเซล",
    icon: headIcon3,
    bgImage: productHead3,
    category: PRODUCT_CATEGORY.MONITOR,
  },
];
